using System.Collections.Generic;

namespace Calme.Domain.Models
{
    public class CategoryMatches
    {
        public static IDictionary<string, Category> Items = new Dictionary<string, Category>
        {

            {"800 DEGREES LIMITE BRIGHTON", Category.Subsistence},
            {"ABOKADO LUDGATE LUDGATE", Category.Subsistence},
            {"ACCOUNTSNET", Category.Exclude},
            {"AGAPE MINISTRIES L 1041020 CHEOL BAEK", Category.Charity},
            {"AIRBNB\\s[0-9]+", Category.Travel},
            {"ALBION 020 7583 0227", Category.Subsistence},
            {"ANDREW CHAA ANDY HALIFAX", Category.Dividend},
            {"ANDREW TSB EMPLOYEE", Category.Dividend},
            {"APPLEGREEN PALMERS PALMERS GREEN", Category.Subsistence},
            {"APPLE STORE R[0-9]+ LONDON", Category.Equipment},
            {"ARK CONVENIENCES LONDON  E4", Category.Subsistence},
            {"ARGOS LTD CHEAPSIDE EC2", Category.Equipment},
            {"ARROWS GROUP PROFE ARROWS GROUP PROFE", Category.Sales},
            {"AROMA CHINGFORD LT CHINGFORD", Category.Subsistence},
            {"AMT COFFEE LONDON [0-9]+", Category.Subsistence},
            {"BARTS SERCO PARKING PERMI", Category.CarParking},
            {"BHCC-PAYPHONEPARKI BRIGHTON", Category.CarParking},
            {"BILLS EASTBOURNE EASTBOURNE", Category.Subsistence},
            {"BIRLEYS SANDWICHES LONDON", Category.Subsistence},
            {"BOOTS0803 LONDON", Category.Subsistence},
            {"Breeze Mezze Resta London", Category.Subsistence},
            {"BRISTOL CITY COUNC BRISTOL", Category.CarParking},
            {"BRISTOL PACKET LTD BRISTOL", Category.CarParking},
            {"BROWNS LONDON  18840", Category.Subsistence},
            {"BT WIFI WITH FON INTERNET", Category.Communication},
            {"BUCKHURST INN BUCKHURST HIL", Category.Subsistence},
            {"BURGER KING LONDON", Category.Subsistence},
            {"B & Q [0-9]+ LONDON", Category.Equipment},
            {"CAFFE NERO 337 VIC LONDON", Category.Subsistence},
            {"CAFFE NERO BRISTOL - CLI", Category.Subsistence},
            {"CAFFE NERO EASTBOU EASTBOURNE", Category.Subsistence},
            {"CAFFE VERGANO 1882 LONDON  WC1V", Category.Subsistence},
            {"CAMINO BANKSIDE LONDON", Category.Subsistence},
            {"CHEEKY CHICOS LIMI LONDON  EC4V", Category.Subsistence},
            {"CINEWORLD ENF CP 0844 815 7747", Category.Subsistence},
            {"CO-OP GROUP FOOD [A-Z0-9]+", Category.Subsistence},
            {"CO-OP GROUP PETROL [A-Z0-9]+", Category.Mileage},
            {"COSTA @ TESCO 4303 LONDON  E4", Category.Subsistence},
            {"COSTA COFFEE CHINGFORD", Category.Subsistence},
            {"COSTA COFFEE WALTHAMSTOW", Category.Subsistence},
            {"CURRYS ONLINE HEMEL HEMPSTE", Category.Equipment},
            {"DART-CHARGE GOV.UK/DART-C", Category.CarParking},
            {"DELICE DE FRANCE B LONDON", Category.Subsistence},
            {"EAT 1997 LONDON EC2M", Category.Subsistence},
            {"ECONOMIST SUBSCRIP LONDON", Category.Subscriptions},
            {"FRANCO MANCA LONDON", Category.Subsistence},
            {"FIVE GUYS LONDON", Category.Subsistence},
            {"Fusciardis Ice Cre Eastbourne", Category.Subsistence},
            {"GIFFGAFF WWW.GIFFGAFF", Category.Communication},
            {"GBK GREENWICH LONDON  SE10", Category.Subsistence},
            {"GREGGS CHINGFORD", Category.Subsistence},
            {"H3G", Category.Communication},
            {"HARE AND TORTOISE LONDON", Category.Subsistence},
            {"HANADAL LTD LONDON  WC1V", Category.Subsistence},
            {"HILLSONG CHURCH 0207 3849200", Category.Charity},
            {"H MART MINI LONDON", Category.Subsistence},
            {"HMRC VAT", Category.Vat},
            {"IKEA LIMITED EDMONTON REST", Category.Equipment},
            {"IKEA LIMITED EDMONTON SACA", Category.Equipment},
            {"INN OF COURT LONDON EC1N", Category.Subsistence},
            {"INT'L [0-9]+ Pluralsight [0-9|-]+ USD [0-9|\\.]+ @[0-9|\\.]+ Visa Rate", Category.Software},
            {"INT'L [0-9]+ Amazon Digital Dwn [0-9|-]+", Category.Book},
            {"INT'L [0-9]+ PAYGATE_INTERNET S SEOUL KRW[0-9]+ @[0-9|\\.]+ Visa R", Category.Book},
            {"INT'L [0-9]+ AMAZON SVCS EU-UK AMAZON.CO.UK", Category.Equipment},
            {"INT'L [0-9]+ Amazon web service aws.amazon.co USD 15.59 @ 1.3532  Visa Rate", Category.Software},
            {"INT'L [0-9]+ AWS #[0-9]+ aws.amazon.co USD [0-9|\\.]+ @ [0-9|\\.]+  Visa Rate", Category.Software},
            {"INT'L [0-9]+ Amazon UK Marketpl 800-279-6620", Category.Equipment},
            {"INT'L [0-9]+ AMAZON EU AMAZON.C AMAZON.CO.UK", Category.Equipment},
            {"INT'L [0-9]+ Amazon UK Marketpl [0-9|-]+", Category.Equipment},
            {"INT'L [0-9]+ Amazon web service aws.amazon.co USD 0.61 @ 1.3863  Visa Rate", Category.Software},
            {"INT'L [0-9]+ UBER EATS [A-Z0-9]+ HE help.uber.com", Category.Subsistence},
            {"INT'L [0-9]+ ITUNES.COM/BILL ITUNES.COM", Category.Software},
            {"INT'L [0-9]+ Kindle Unlimited Amazon.co.uk", Category.Subscriptions},
            {"INT'L [0-9]+ 1105 MEDIA SUBSCRP 818-814-5200 USD 65.00 @ 1.4220  Visa Rate", Category.Subscriptions},
            {"INT'L [0-9]+ Amazon UK Retail AMAZON.CO.UK", Category.Equipment},
            {"INT'L [0-9]+ AMAZON PRIME MEMBE AMZN.CO.UK/PM", Category.Subscriptions},
            {"INT'L [0-9]+ NAME-CHEAP.COM WWW.NAMECHEAP USD [0-9|\\.]+ @ [0-9|\\.]+  Visa Rate", Category.Software},
            {"Just Eat London", Category.Subsistence},
            {"KFC - ARCHWAY ARCHWAY", Category.Subsistence},
            {"KIMCHEE HOLBORN LONDON", Category.Subsistence},
            {"LABOITE LONDON  E4", Category.Subsistence},
            {"Le Petit Corner Leytonstone", Category.Subsistence},
            {"LOTUS LEAF LONDON", Category.Subsistence},
            {"M&S SIMPLY FOOD - LIVERPOOL ST", Category.Subsistence},
            {"MARKS&SPENCER PLC STRATFORD", Category.Subsistence},
            {"MARRAKECH DELIGHT LONDON", Category.Subsistence},
            {"MCDONALD'S COUNTY HALL L", Category.Subsistence},
            {"MCDONALDS CANNING TOWN", Category.Subsistence},
            {"MCDONALDS LONDON  E7", Category.Subsistence},
            {"MCDONALDS LONDON  EC2M", Category.Subsistence},
            {"MORRISON PETROL LONDON E4 001", Category.Mileage},
            {"MOTO READING EAST READING", Category.Subsistence},
            {"MOTO READING WT CO READING", Category.Subsistence},
            {"Non-Sterling Transaction Fee", Category.Sundries},
            {"NOO NOODLES LONDON", Category.Subsistence},
            {"PATISSERIE VALERIE EASTBOURNE", Category.Subsistence},
            {"PAUL UK ST PAULS LONDON", Category.Subsistence},
            {"PAYPAL *LKH10915 35314369001", Category.Equipment},
            {"PAYPAL *LOVERBRAND 35314369001", Category.Equipment},
            {"PHO BRISTOL BRISTOL", Category.Subsistence},
            {"PHO ST PAUL'S LONDON", Category.Subsistence},
            {"PIZZA EXPRESS LONDON  3223", Category.Subsistence},
            {"POD LONDON", Category.Subsistence},
            {"POUNDLAND LTD LONDON  E17", Category.Stationery},
            {"PRET A MANGER 10 PATERNOSTE", Category.Subsistence},
            {"PRET A MANGER BROADGATE LIN", Category.Subsistence},
            {"PRET A MANGER FLEETPLATE HO", Category.Subsistence},
            {"SAINSBURYS S/MKTS FETTER LANE", Category.Subsistence},
            {"SAINSBURYS S/MKTS LONDON 0002", Category.Subsistence},
            {"SAINSBURYS S/MKTS LONDON PATERN", Category.Subsistence},
            {"SAINSBURYS S/MKTS MID CITY PLAC", Category.Subsistence},
            {"SAINSBURYS S/MKTS TOWER HAMLETS", Category.Subsistence},
            {"SODO PIZZA LONDON", Category.Subsistence},
            {"Spotify P0564C5D7E London", Category.Software},
            {"Spotify P05C06E21F London", Category.Software},
            {"SS GT BRITAIN TRAD BRISTOL", Category.Subsistence},
            {"ST PANCRAS INTL LONDON", Category.PublicTransport},
            {"STARBUCKS 1 CONCOU LONDON", Category.Subsistence},
            {"STARBUCKS CARD REL 8452703310", Category.Subsistence},
            {"STARBUCKS EASTBOUR EASTBOURNE", Category.Subsistence},
            {"STARBUCKS LONDON EC2M", Category.Subsistence},
            {"STARBUCKS LONDON", Category.Subsistence},
            {"STICKS & BROTH BRISTOL BS1", Category.Subsistence},
            {"SWEETHEART LONDON  WC2E", Category.Subsistence},
            {"TANAKATSU AT RIBON LONDON", Category.Subsistence},
            {"TESCO PFS 3916 EASTBOURNE 2", Category.Subsistence},
            {"TESCO STORES 5158 LONDON", Category.Subsistence},
            {"TESCO STORES 5327 HIGHAMS PARK", Category.Subsistence},
            {"TESCO STORES 6339 CHINGFORD", Category.Subsistence},
            {"TESCO STORES 6977 WALTHAMSTOW", Category.Subsistence},
            {"TFL OYST PHOTOCARD 0343 222 1234", Category.PublicTransport},
            {"THAI EXPRESS LONDON", Category.Subsistence},
            {"THE ARGYLE LONDON LONDON", Category.Subsistence},
            {"THE JAPANESE CANTE LONDON", Category.Subsistence},
            {"THE VILLAGE LONDON", Category.Subsistence},
            {"THEWORKS CHINGFORD", Category.Subsistence},
            {"TOSSED LONDON  EC1A", Category.Subsistence},
            {"TRAINLINE LONDON", Category.PublicTransport},
            {"UPPER CRUST BARRIE LONDON", Category.Subsistence},
            {"VENDING SOLUTIONS SOUTHAMPTON", Category.Subsistence},
            {"VICTORIA SQUARE HO BRISTOL", Category.PublicTransport},
            {"VIRGIN MEDIA PYMTS", Category.Communication},
            {"WAGAMAMA ROYAL FES LONDON", Category.Subsistence},
            {"WASABI HIGH HOLBOR LONDON", Category.Subsistence},
            {"WASABI VICTORIA ST LONDON", Category.Subsistence},
            {"WWW.ALIEXPRESS.COM INTERNET", Category.Equipment},
            {"WWW.DOMINOS.CO.UK 01908 580000", Category.Subsistence},
            {"WWW.JUST-EAT.CO.UK 02067 362061", Category.Subsistence},
            {"WWW.TFL.GOV.UK 0343 2221234", Category.PublicTransport},
            {"YEN LONDON  EC1A", Category.Subsistence},
            {"YOKU SUSHI LIMITED EASTBOURNE", Category.Subsistence},

        };



    }
}