using System.Collections.Generic;

namespace Calme.Domain.Models
{
    public class CategoryMatches
    {
        public static IDictionary<string, Category> HsbcItems = new Dictionary<string, Category>
        {
            {"800 DEGREES LIMITE BRIGHTON", Category.Subsistence},
            {"ABOKADO LUDGATE LUDGATE", Category.Subsistence},
            {"ACCOUNTSNET", Category.Exclude},
            {"AGAPE MINISTRIES L 1041020 CHEOL BAEK", Category.Charity},
            {"AIRBNB\\s[0-9]+", Category.Travel},
            {"ALBION 020 7583 0227", Category.Subsistence},
            {"ANDREW CHAA ANDY HALIFAX", Category.Dividend},
            {"ANDREW TSB EMPLOYEE", Category.Dividend},
            {"APPLEGREEN PALMERS PALMERS GREEN", Category.Subsistence},
            {"APPLE STORE R[0-9]+ LONDON", Category.Equipment},
            {"ARK CONVENIENCES LONDON  E4", Category.Subsistence},
            {"ARGOS LTD CHEAPSIDE EC2", Category.Equipment},
            {"ARROWS GROUP PROFE ARROWS GROUP PROFE", Category.Sales},
            {"AROMA CHINGFORD LT CHINGFORD", Category.Subsistence},
            {"AMT COFFEE LONDON [0-9]+", Category.Subsistence},
            {"BANH MI BAY LONDON", Category.Subsistence},
            {"BARTS SERCO PARKING PERMI", Category.CarParking},
            {"BHCC-PAYPHONEPARKI BRIGHTON", Category.CarParking},
            {"BILLS EASTBOURNE EASTBOURNE", Category.Subsistence},
            {"BIRLEYS SANDWICHES LONDON", Category.Subsistence},
            {"BOOTS0803 LONDON", Category.Subsistence},
            {"BP CHURCH VIEW CON TUNBRIDGE WEL", Category.Subsistence},
            {"Breeze Mezze Resta London", Category.Subsistence},
            {"BRISTOL CITY COUNC BRISTOL", Category.CarParking},
            {"BRISTOL PACKET LTD BRISTOL", Category.CarParking},
            {"BROWNS LONDON  18840", Category.Subsistence},
            {"BT WIFI WITH FON INTERNET", Category.Communication},
            {"BUCKHURST INN BUCKHURST HIL", Category.Subsistence},
            {"BURGER KING LONDON", Category.Subsistence},
            {"B & Q [0-9]+ LONDON", Category.Equipment},
            {"CAFFE NERO 337 VIC LONDON", Category.Subsistence},
            {"CAFFE NERO BRISTOL - CLI", Category.Subsistence},
            {"CAFFE NERO EASTBOU EASTBOURNE", Category.Subsistence},
            {"CAFFE VERGANO 1882 LONDON  WC1V", Category.Subsistence},
            {"CAMBRIDGE THEATRE LONDON  WC2", Category.Subsistence},
            {"CAMINO BANKSIDE LONDON", Category.Subsistence}, 
            {"CHEEKY CHICOS LIMI LONDON  EC4V", Category.Subsistence},
            {"CINEWORLD ENF CP 0844 815 7747", Category.Subsistence},
            {"CRUSSH FIT FOOD LONDON  EC4M", Category.Subsistence},
            {"A CLOUD GURU TWICKENHAM", Category.Software},
            {"CO-OP GROUP FOOD [A-Z0-9]+", Category.Subsistence},
            {"CO-OP GROUP PETROL [A-Z0-9]+", Category.Mileage},
            {"COSTA @ TESCO 4303 LONDON  E4", Category.Subsistence},
            {"COSTA COFFEE CHINGFORD", Category.Subsistence},
            {"COSTA COFFEE WALTHAMSTOW", Category.Subsistence},
            {"CURRYS ONLINE HEMEL HEMPSTE", Category.Equipment},
            {"DART-CHARGE GOV.UK/DART-C", Category.CarParking},
            {"DELICE DE FRANCE B LONDON", Category.Subsistence},
            {"EAT 1997 LONDON EC2M", Category.Subsistence},
            {"ECONOMIST SUBSCRIP LONDON", Category.Subscriptions},
            {"EUROSTAR INTERNET LONDON", Category.PublicTransport},
            {"FRANCO MANCA LONDON", Category.Subsistence},
            {"FIVE GUYS LONDON", Category.Subsistence},
            {"Fusciardis Ice Cre Eastbourne", Category.Subsistence},
            {"GIFFGAFF WWW.GIFFGAFF", Category.Communication},
            {"GIVE ME EXTRA EASTBOURNE", Category.Subsistence},
            {"GBK GREENWICH LONDON  SE10", Category.Subsistence},
            {"GOOGLE \\*Google Sto g.co/helppay#", Category.Subsistence},
            {"GREGGS CHINGFORD", Category.Subsistence},
            {"H3G", Category.Communication},
            {"HARE AND TORTOISE LONDON", Category.Subsistence},
            {"HANADAL LTD LONDON  WC1V", Category.Subsistence},
            {"HIGHAMS LOUNGE LONDON", Category.Subsistence},
            {"H/VSTER CHINGFORD 0208 5292990", Category.Subsistence},
            {"HILLSONG CHURCH 0207 3849200", Category.Charity},
            {"H MART MINI LONDON", Category.Subsistence},
            {"HMRC VAT", Category.Vat},
            {"ICELAND PENGE", Category.Subsistence},
            {"IKEA LIMITED EDMONTON REST", Category.Subsistence},
            {"IKEA LIMITED EDMONTON(\\sSACA)?", Category.Fixture},
            {"INN OF COURT LONDON EC1N", Category.Subsistence},
            {"INT'L [0-9]+ Pluralsight [0-9|-]+ USD [0-9|\\.]+ @[0-9|\\.]+ Visa Rate", Category.Software},
            {"INT'L [0-9]+ Amazon Digital Dwn [0-9|-]+", Category.Book},
            {"INT'L [0-9]+ Amazon.co.uk AMAZON.CO.UK", Category.Equipment},
            {"INT'L [0-9]+ AMZN Mktp UK.*", Category.Equipment},
            {"INT'L [0-9]+ AMAZON SVCS EU-UK AMAZON.CO.UK", Category.Equipment},
            {"INT'L [0-9]+ Amazon web service aws.amazon.co USD 15.59 @ 1.3532  Visa Rate", Category.Software},
            {"INT'L [0-9]+ Amazon UK Marketpl 800-279-6620", Category.Equipment},
            {"INT'L [0-9]+ AMAZON EU AMAZON.C AMAZON.CO.UK", Category.Equipment},
            {"INT'L [0-9]+ Amazon UK Marketpl [0-9|-]+", Category.Equipment},
            {"INT'L [0-9]+ Amazon UK Retail AMAZON.CO.UK", Category.Equipment},
            {"INT'L [0-9]+ AMAZON PRIME MEMBE AMZN.CO.UK/PM", Category.Subscriptions},
            {"INT'L [0-9]+ Amazon web service aws.amazon.co USD 0.61 @ 1.3863  Visa Rate", Category.Software},
            {"INT'L [0-9]+ AWS EMEA (#[0-9|\\s])*aws\\.amazon\\.co USD [0-9|\\.]+ @ [0-9|\\.]+  Visa Rate", Category.Software},
            {"INT'L [0-9]+ AUCHAN VAL D'EUROP 77000", Category.Subsistence},
            {"INT'L [0-9]+ PAYGATE_INTERNET S SEOUL KRW[0-9]+ @[0-9|\\.]+ Visa R", Category.Book},
            {"INT'L [0-9]+ UBER EATS [A-Z0-9]+ HE help.uber.com", Category.Subsistence},
            {"INT'L [0-9]+ UBER\\s+\\*EATS [A-Z0-9]+ [0-9|-]+", Category.Subsistence},
            {"INT'L [0-9]+ UBER TRIP [A-Z0-9]+ HE help\\.uber\\.com(.+)?", Category.PublicTransport},
            {"INT'L [0-9]+ ITUNES.COM/BILL ITUNES.COM", Category.Software},
            {"INT'L [0-9]+ Kindle Unlimited Amazon.co.uk", Category.Subscriptions},
            {"INT'L [0-9]+ 1105 MEDIA SUBSCRP 818-814-5200 USD 65.00 @ 1.4220  Visa Rate", Category.Subscriptions},
            {"INT'L [0-9]+ NAME-CHEAP.COM WWW.NAMECHEAP USD [0-9|\\.]+ @ [0-9|\\.]+  Visa Rate", Category.Software},
            {"ISMASH UK TRADING LONDON", Category.Equipment},
            {"IZ \\*DELICE Emilia LONDON", Category.Subsistence},
            {"IZ \\*Foodgangnamsty New malden", Category.Subsistence},
            {"IZ \\*Handcrafted Co London", Category.Subsistence},
            {"IZ \\*KOTTU AND HOPP London", Category.Subsistence},
            {"IZ \\*PRIME GELATO L London", Category.Subsistence},
            {"IZ \\*THE GREEN CAFE HASTINGS", Category.Subsistence},
            {"IZ \\*Urban Ground EASTBOURNE", Category.Subsistence},
            {"KFC - ARCHWAY ARCHWAY", Category.Subsistence},
            {"Just Eat London", Category.Subsistence},
            {"JUSTPARK LONDON", Category.CarParking},
            {"KIMCHEE HOLBORN LONDON", Category.Subsistence},
            {"KIMCHEE TO GO 106 LONDON", Category.Subsistence},
            {"LABOITE LONDON  E4", Category.Subsistence},
            {"Le Petit Corner Leytonstone", Category.Subsistence},
            {"LIME ORANGE LONDON  SW1V", Category.Subsistence},
            {"LITTLE ITALY EASTBOURNE BN", Category.Subsistence},
            {"LOTUS LEAF LONDON", Category.Subsistence},
            {"M&S SIMPLY FOOD - .+", Category.Subsistence},
            {"MARKS&SPENCER PLC [A-Z]+", Category.Subsistence},
            {"MARRAKECH DELIGHT LONDON", Category.Subsistence},
            {"MCDONALD'?S [A-Z]+ \\s? [A-Z|0-9]+", Category.Subsistence},
            {"MORRISON PETROL LONDON E4 001", Category.Subsistence},
            {"MOTO READING EAST READING", Category.Subsistence},
            {"MOTO READING WT CO READING", Category.Subsistence},
            {"NANDOS LOUGHTON LOUGHTON", Category.Subsistence},
            {"NISA EASTBOURNE", Category.Subsistence},
            {"Non-Sterling Transaction Fee", Category.Sundries},
            {"NOO NOODLES LONDON", Category.Subsistence},
            {"PATISSERIE VALERIE EASTBOURNE", Category.Subsistence},
            {"PIZZAEXPRESS RESTA WALTHANSTOW", Category.Subsistence},
            {"OYSTER [A-Z|-]+ [A-Z]+ [0-9]+ [0-9]+", Category.PublicTransport},
            {"PAUL UK ST PAULS LONDON", Category.Subsistence},
            {"PAYBYPHONE HATFIELD", Category.CarParking},
            {"PAYPAL \\*[A-Z]+ [0-9]+", Category.Equipment},
            {"PHO [A-Z|'|\\s]+ [A-Z]+", Category.Subsistence},
            {"PIZZA EXPRESS [A-Z]+ [A-Z]+", Category.Subsistence},
            {"POST OFFICE COUNTE LONDON", Category.Postage},
            {"RINGGO PARKING 18", Category.CarParking},
            {"ROSAS WESTFIELD ST LONDON", Category.Subsistence},
            {"POD LONDON", Category.Subsistence},
            {"POUNDLAND LTD LONDON  E17", Category.Stationery},
            {"PRET A MANGER [0-9|A-Z]* \\s?[A-Z|0-9]*", Category.Subsistence},
            {"SAINSBURYS S/MKTS [A-Z]+[A-Z|0-9|\\s]*", Category.Subsistence},
            {"SATAY STREET 02074260017", Category.Subsistence},
            {"SHAKE SHACK WATFORD", Category.Subsistence},
            {"SHELL LARKSHALL RD CHINGFORD", Category.Subsistence},
            {"SHORYU STRATFORD LONDON", Category.Subsistence},
            {"SODO PIZZA LONDON", Category.Subsistence},
            {"SPICY & GRILL LONDON NW11", Category.Subsistence},
            {"Spotify [A-Z|0-9]+ London", Category.Software},
            {"SS GT BRITAIN TRAD BRISTOL", Category.Subsistence},
            {"ST PANCRAS INTL LONDON", Category.PublicTransport},
            {"STARBUCKS 1 CONCOU LONDON", Category.Subsistence},
            {"STARBUCKS CARD REL 8452703310", Category.Subsistence},
            {"STARBUCKS EASTBOUR EASTBOURNE", Category.Subsistence},
            {"STARBUCKS LONDON EC2M", Category.Subsistence},
            {"STARBUCKS LONDON", Category.Subsistence},
            {"STICKS & BROTH BRISTOL BS1", Category.Subsistence},
            {"SUPPA LONDON  EC1A", Category.Subsistence},
            {"SWEETHEART LONDON  WC2E", Category.Subsistence},
            {"TANAKATSU AT RIBON LONDON", Category.Subsistence},
            {"TESCO PFS 3916 EASTBOURNE 2", Category.Subsistence},
            {"TESCO STORES [0-9]+ [A-Z|\\s]+", Category.Subsistence},
            {"TFL OYST PHOTOCARD 0343 222 1234", Category.PublicTransport},
            {"TFL TRAVEL [A-Z]+ TFL.GOV.UK/CP", Category.PublicTransport},
            {"T G I FRIDAY'S ENFIELD 680", Category.Subsistence},
            {"THAI EXPRESS LONDON", Category.Subsistence},
            {"THE ARGYLE LONDON LONDON", Category.Subsistence},
            {"THE ASSOCIATION LONDON  EC4M", Category.Subsistence},
            {"THE CHEEKY INDIAN UXBRIDGE", Category.Subsistence},
            {"THE JAPANESE CANTE LONDON", Category.Subsistence},
            {"THE VILLAGE LONDON", Category.Subsistence},
            {"THEWORKS CHINGFORD", Category.Subsistence},
            {"TOSSED LONDON  EC1A", Category.Subsistence},
            {"TRAINLINE LONDON", Category.PublicTransport},
            {"UBER EATS [A-Z|0-9]+ HE help.uber.com", Category.Subsistence},
            {"UBER TRIP [A-Z|0-9]+ HE help.uber.com", Category.PublicTransport},
            {"UPPER CRUST BARRIE LONDON", Category.Subsistence},
            {"VAPIANO [A-Z|\\s]*LONDON.*", Category.Subsistence},
            {"VENDING SOLUTIONS SOUTHAMPTON", Category.Subsistence},
            {"VICTORIA SQUARE HO BRISTOL", Category.PublicTransport},
            {"VIRGIN MEDIA PYMTS", Category.Communication},
            {"WAGAMAMA .*", Category.Subsistence},
            {"WAHACA ST PAULS LONDON", Category.Subsistence},
            {"WASABI [A-Z]+ [A-Z]+ LONDON", Category.Subsistence},
            {"WELLBEING KITCHEN LONDON  WC2H", Category.Subsistence},
            {"WWW.ALIEXPRESS.COM INTERNET", Category.Equipment},
            {"WWW.DOMINOS.CO.UK 01908 580000", Category.Subsistence},
            {"WWW.IKEA.COM PETERBOROUGH", Category.Fixture},
            {"WWW.JUST-EAT.CO.UK 02067 362061", Category.Subsistence},
            {"WWW.TFL.GOV.UK 0343 2221234", Category.PublicTransport},
            {"YEN LONDON  EC1A", Category.Subsistence},
            {"YOKU SUSHI LIMITED [A-Z|0-9]+", Category.Subsistence},

        };


    }
}