using System.Collections.Concurrent;
using System.Collections.Generic;

namespace QuickExpense.Domain.Models
{
    public class Categories
    {
        public static IDictionary<string, string> Items = new Dictionary<string, string>
        {
            { "ACCOUNTSNET", "Exclude" }, 
            { "AGAPE MINISTRIES L 1041020 CHEOL BAEK", "Charity" },
                { "ANDREW CHAA ANDY HALIFAX", "Dividend" },
                { "ANDREW TSB EMPLOYEE", "Dividend" },
                { "APPLEGREEN PALMERS PALMERS GREEN", "Subsistence" },
                { "ARROWS GROUP PROFE ARROWS GROUP PROFE", "Sales" },
                { "BARTS SERCO PARKING PERMI", "Car Parking" },
                { "BHCC-PAYPHONEPARKI BRIGHTON", "Car Parking" },
                { "Breeze Mezze Resta London", "Subsistence" },
                { "BRISTOL CITY COUNC BRISTOL", "Car Parking" },
                { "BRISTOL PACKET LTD BRISTOL", "Car Parking" },
                { "BROWNS LONDON  18840", "Subsistence" },
                { "BT WIFI WITH FON INTERNET", "Comm" },
                { "CAFFE NERO BRISTOL - CLI", "Subsistence" },
                { "CAFFE NERO EASTBOU EASTBOURNE", "Subsistence" },
                { "CINEWORLD ENF CP 0844 815 7747", "Subsistence" },
                { "COSTA COFFEE CHINGFORD", "Subsistence" },
                { "DART-CHARGE GOV.UK/DART-C", "Car Parking" },
                { "ECONOMIST SUBSCRIP LONDON", "Subscriptions" },
                { "GIFFGAFF WWW.GIFFGAFF", "Comm" },
                { "H3G", "Comm" },
                { "HILLSONG CHURCH 0207 3849200", "Charity" },
                { "HMRC VAT", "VAT" },
                { "INN OF COURT LONDON EC1N", "Subsistence" },
                { "INT'L 0002002921 AMAZON SVCS EU-UK AMAZON.CO.UK", "Equipment" },
                { "INT'L 0027632705 Amazon web service aws.amazon.co USD 0.61 @ 1.3863  Visa Rate", "Software" },
                { "INT'L 0033411148 UBER EATS JLR55 HE help.uber.com", "Subsistence" },
                { "INT'L 0065499908 ITUNES.COM/BILL ITUNES.COM", "Software" },
                { "INT'L 0067371104 Kindle Unlimited Amazon.co.uk", "Subscriptions" },
                { "INT'L 0068599149 Amazon Digital Dwn 866-321-8851", "Software" },
                { "INT'L 0068599150 UBER EATS HT4B5 HE help.uber.com", "Subsistence" },
                { "INT'L 0084827059 1105 MEDIA SUBSCRP 818-814-5200 USD 65.00 @ 1.4220  Visa Rate", "Subscriptions" },
                { "INT'L 0090697151 AMAZON PRIME MEMBE AMZN.CO.UK/PM", "Subscriptions" },
                { "INT'L 0094092544 UBER TRIP BH7UF HE help.uber.com", "Travel" },
                { "INT'L 0099965866 AMAZON SVCS EU-UK AMAZON.CO.UK", "Equipment" },
                { "Just Eat London", "Subsistence" },
                { "KIMCHEE HOLBORN LONDON", "Subsistence" },
                { "LABOITE LONDON  E4", "Subsistence" },
                { "LOTUS LEAF LONDON", "Subsistence" },
                { "M&S SIMPLY FOOD - LIVERPOOL ST", "Subsistence" },
                { "MARKS&SPENCER PLC STRATFORD", "Subsistence" },
                { "MCDONALDS CANNING TOWN", "Subsistence" },
                { "MCDONALDS LONDON  E7", "Subsistence" },
                { "MORRISON PETROL LONDON E4 001", "Mileage" },
                { "MOTO READING EAST, READING", "Subsistence" },
                { "MOTO READING WT CO READING", "Subsistence" },
                { "Non-Sterling Transaction Fee", "Sundries" },
                { "PATISSERIE VALERIE EASTBOURNE", "Subsistence" },
                { "PAUL UK ST PAULS LONDON", "Subsistence" },
                { "PAYPAL *LOVERBRAND 35314369001", "Equipment" },
                { "PHO BRISTOL BRISTOL", "Subsistence" },
                { "PHO ST PAUL'S LONDON", "Subsistence" },
                { "PIZZA EXPRESS LONDON  3223", "Subsistence" },
                { "POD LONDON", "Subsistence" },
                { "PRET A MANGER 10 PATERNOSTE", "Subsistence" },
                { "PRET A MANGER FLEETPLATE HO", "Subsistence" },
                { "SAINSBURYS S/MKTS FETTER LANE", "Subsistence" },
                { "SAINSBURYS S/MKTS LONDON 0002", "Subsistence" },
                { "SAINSBURYS S/MKTS LONDON PATERN", "Subsistence" },
                { "SAINSBURYS S/MKTS MID CITY PLAC", "Subsistence" },
                { "SODO PIZZA LONDON", "Subsistence" },
                { "Spotify P0564C5D7E London", "Software" },
                { "SS GT BRITAIN TRAD BRISTOL", "Subsistence" },
                { "ST PANCRAS INTL LONDON", "Travel" },
                { "STARBUCKS 1 CONCOU LONDON", "Subsistence" },
                { "STARBUCKS CARD REL 8452703310", "Subsistence" },
                { "STARBUCKS EASTBOUR EASTBOURNE", "Subsistence" },
                { "STARBUCKS LONDON", "Subsistence" },
                { "STARBUCKS LONDON EC2M", "Subsistence" },
                { "STICKS & BROTH BRISTOL BS1", "Subsistence" },
                { "TANAKATSU AT RIBON LONDON", "Subsistence" },
                { "TESCO PFS 3916 EASTBOURNE 2", "Subsistence" },
                { "TESCO STORES 5158 LONDON", "Subsistence" },
                { "TESCO STORES 6339 CHINGFORD", "Subsistence" },
                { "TESCO STORES 6977 WALTHAMSTOW", "Subsistence" },
                { "TFL OYST PHOTOCARD 0343 222 1234", "Travel" },
                { "THAI EXPRESS LONDON", "Subsistence" },
                { "THE ARGYLE LONDON LONDON", "Subsistence" },
                { "THE JAPANESE CANTE LONDON", "Subsistence" },
                { "THE VILLAGE LONDON", "Subsistence" },
                { "VENDING SOLUTIONS SOUTHAMPTON", "Subsistence" },
                { "VICTORIA SQUARE HO BRISTOL", "Travel" },
                { "VIRGIN MEDIA PYMTS", "Comm" },
                { "WAGAMAMA ROYAL FES LONDON", "Subsistence" },
                { "WASABI HIGH HOLBOR LONDON", "Subsistence" },
                { "WWW.ALIEXPRESS.COM INTERNET", "Equipment" },
                { "WWW.JUST-EAT.CO.UK 02067 362061", "Subsistence" },
                { "WWW.TFL.GOV.UK 0343 2221234", "Travel" },
                { "YEN LONDON  EC1A", "Subsistence" },
                { "YOKU SUSHI LIMITED EASTBOURNE", "Subsistence" }

        };
        
       
        
    }
}