using System.Collections.Concurrent;
using System.Collections.Generic;

namespace QuickExpense.Domain.Models
{
    public class Categories
    {
        public static IDictionary<string, Category> Items = new Dictionary<string, Category>
        {
            
            { "INT'L 0062957828 PAYGATE_INTERNET S SEOUL KRW100000 @1436.1625 Visa R", Category.Book },
            
            { "BARTS SERCO PARKING PERMI", Category.CarParking },
            { "BHCC-PAYPHONEPARKI BRIGHTON", Category.CarParking },
            { "BRISTOL CITY COUNC BRISTOL", Category.CarParking },
            { "DART-CHARGE GOV.UK/DART-C", Category.CarParking },
            
            { "HILLSONG CHURCH 0207 3849200", Category.Charity },

            { "BT WIFI WITH FON INTERNET", Category.Communication },
            { "GIFFGAFF WWW.GIFFGAFF", Category.Communication },
            { "H3G", Category.Communication },
            { "VIRGIN MEDIA PYMTS", Category.Communication },

            { "PAYPAL *LKH10915 35314369001", Category.Equipment },
            { "INT'L 0086375539 Amazon UK Retail AMAZON.CO.UK", Category.Equipment },
            { "INT'L 0092394162 Amazon UK Retail AMAZON.CO.UK", Category.Equipment },
            { "INT'L 0086375542 Amazon UK Retail AMAZON.CO.UK", Category.Equipment },
            { "INT'L 0086375540 Amazon UK Retail AMAZON.CO.UK", Category.Equipment },
            { "INT'L 0086375541 Amazon UK Marketpl 800-279-6620", Category.Equipment },
            { "INT'L 0080378185 AMAZON SVCS EU-UK AMAZON.CO.UK", Category.Equipment },
            { "INT'L 0003795286 Amazon UK Marketpl 800-279-6620", Category.Equipment },
            { "INT'L 0009520506 AMAZON EU AMAZON.C AMAZON.CO.UK", Category.Equipment },
            { "INT'L 0020438335 Amazon UK Marketpl 800-279-6620", Category.Equipment },
            { "INT'L 0038572764 Amazon UK Marketpl 800-279-6620", Category.Equipment },
            { "INT'L 0045083891 Amazon Digital Dwn 866-321-8851", Category.Equipment },
            { "CURRYS ONLINE HEMEL HEMPSTE", Category.Equipment },
            { "IKEA LIMITED EDMONTON REST", Category.Equipment },
            { "IKEA LIMITED EDMONTON SACA", Category.Equipment },
            { "ARGOS LTD CHEAPSIDE EC2", Category.Equipment },
            { "INT'L 0002002921 AMAZON SVCS EU-UK AMAZON.CO.UK", Category.Equipment },
            { "INT'L 0099965866 AMAZON SVCS EU-UK AMAZON.CO.UK", Category.Equipment },
            { "WWW.ALIEXPRESS.COM INTERNET", Category.Equipment },
            { "PAYPAL *LOVERBRAND 35314369001", Category.Equipment },

            { "ACCOUNTSNET", Category.Exclude }, 

            { "MORRISON PETROL LONDON E4 001", Category.Mileage },

            { "INT'L 0094092544 UBER TRIP BH7UF HE help.uber.com", Category.PublicTransport },
            { "ST PANCRAS INTL LONDON", Category.PublicTransport },
            { "TFL OYST PHOTOCARD 0343 222 1234", Category.PublicTransport },
            { "VICTORIA SQUARE HO BRISTOL", Category.PublicTransport },
            { "TRAINLINE LONDON", Category.PublicTransport },
            { "WWW.TFL.GOV.UK 0343 2221234", Category.PublicTransport },

            { "ARROWS GROUP PROFE ARROWS GROUP PROFE", Category.Sales },

            { "Spotify P05C06E21F London", Category.Software },
            { "INT'L 0003147479 Amazon web service aws.amazon.co USD 15.59 @ 1.3532  Visa Rate", Category.Software },
            { "INT'L 0065499908 ITUNES.COM/BILL ITUNES.COM", Category.Software },
            { "INT'L 0068599149 Amazon Digital Dwn 866-321-8851", Category.Software },
            { "Spotify P0564C5D7E London", Category.Software },

            { "POUNDLAND LTD LONDON  E17", Category.Stationery },

            { "800 DEGREES LIMITE BRIGHTON", Category.Subsistence },
            { "CO-OP GROUP FOOD LONDON", Category.Subsistence },
            { "BURGER KING LONDON", Category.Subsistence },
            { "CAFFE NERO 337 VIC LONDON", Category.Subsistence },
            { "CAFFE VERGANO 1882 LONDON  WC1V", Category.Subsistence },
            { "CHEEKY CHICOS LIMI LONDON  EC4V", Category.Subsistence },
            { "ABOKADO LUDGATE LUDGATE", Category.Subsistence },
            { "COSTA @ TESCO 4303 LONDON  E4", Category.Subsistence },
            { "COSTA COFFEE WALTHAMSTOW", Category.Subsistence },
            { "AGAPE MINISTRIES L 1041020 CHEOL BAEK", Category.Charity },
            { "ALBION 020 7583 0227", Category.Subsistence },
            { "ANDREW CHAA ANDY HALIFAX", Category.Dividend },
            { "ANDREW TSB EMPLOYEE", Category.Dividend },
            { "APPLEGREEN PALMERS PALMERS GREEN", Category.Subsistence },
            { "FIVE GUYS LONDON", Category.Subsistence },
            { "Fusciardis Ice Cre Eastbourne", Category.Subsistence },
            { "HANADAL LTD LONDON  WC1V", Category.Subsistence },
            { "INT'L 0059453754 UBER EATS 66K4R HE help.uber.com", Category.Subsistence },
            { "INT'L 0059453755 UBER EATS 66K4R HE help.uber.com", Category.Subsistence },
            { "INT'L 0078632893 UBER EATS 7DJZK HE help.uber.com", Category.Subsistence },
            { "INT'L 0078632894 UBER EATS 7DJZK HE help.uber.com", Category.Subsistence },
            { "KFC - ARCHWAY ARCHWAY", Category.Subsistence },
            { "Le Petit Corner Leytonstone", Category.Subsistence },
            { "MARRAKECH DELIGHT LONDON", Category.Subsistence },
            { "MCDONALD'S COUNTY HALL L", Category.Subsistence },
            { "MCDONALDS LONDON  EC2M", Category.Subsistence },
            { "NOO NOODLES LONDON", Category.Subsistence },
            { "PRET A MANGER BROADGATE LIN", Category.Subsistence },
            { "SAINSBURYS S/MKTS TOWER HAMLETS", Category.Subsistence },
            { "SWEETHEART LONDON  WC2E", Category.Subsistence },
            { "TESCO STORES 5327 HIGHAMS PARK", Category.Subsistence },
            { "THEWORKS CHINGFORD", Category.Subsistence },
            { "TOSSED LONDON  EC1A", Category.Subsistence },
            { "UPPER CRUST BARRIE LONDON", Category.Subsistence },
            { "WASABI VICTORIA ST LONDON", Category.Subsistence },
            { "WWW.DOMINOS.CO.UK 01908 580000", Category.Subsistence },
            { "Breeze Mezze Resta London", Category.Subsistence },
            { "BOOTS0803 LONDON", Category.Subsistence },
            { "BROWNS LONDON  18840", Category.Subsistence },
            { "BUCKHURST INN BUCKHURST HIL", Category.Subsistence },
            { "CAFFE NERO BRISTOL - CLI", Category.Subsistence },
            { "CAFFE NERO EASTBOU EASTBOURNE", Category.Subsistence },
            { "CINEWORLD ENF CP 0844 815 7747", Category.Subsistence },
            { "COSTA COFFEE CHINGFORD", Category.Subsistence },
            { "INN OF COURT LONDON EC1N", Category.Subsistence },
            { "INT'L 0033411148 UBER EATS JLR55 HE help.uber.com", Category.Subsistence },
            { "INT'L 0068599150 UBER EATS HT4B5 HE help.uber.com", Category.Subsistence },
            { "Just Eat London", Category.Subsistence },
            { "KIMCHEE HOLBORN LONDON", Category.Subsistence },
            { "LABOITE LONDON  E4", Category.Subsistence },
            { "LOTUS LEAF LONDON", Category.Subsistence },
            { "M&S SIMPLY FOOD - LIVERPOOL ST", Category.Subsistence },
            { "MARKS&SPENCER PLC STRATFORD", Category.Subsistence },
            { "MCDONALDS CANNING TOWN", Category.Subsistence },
            { "MCDONALDS LONDON  E7", Category.Subsistence },
            { "MOTO READING EAST, READING", Category.Subsistence },
            { "MOTO READING WT CO READING", Category.Subsistence },
            { "PATISSERIE VALERIE EASTBOURNE", Category.Subsistence },
            { "PAUL UK ST PAULS LONDON", Category.Subsistence },
            { "PHO BRISTOL BRISTOL", Category.Subsistence },
            { "PHO ST PAUL'S LONDON", Category.Subsistence },
            { "PIZZA EXPRESS LONDON  3223", Category.Subsistence },
            { "POD LONDON", Category.Subsistence },
            { "PRET A MANGER 10 PATERNOSTE", Category.Subsistence },
            { "PRET A MANGER FLEETPLATE HO", Category.Subsistence },
            { "SAINSBURYS S/MKTS FETTER LANE", Category.Subsistence },
            { "SAINSBURYS S/MKTS LONDON 0002", Category.Subsistence },
            { "SAINSBURYS S/MKTS LONDON PATERN", Category.Subsistence },
            { "SAINSBURYS S/MKTS MID CITY PLAC", Category.Subsistence },
            { "SODO PIZZA LONDON", Category.Subsistence },
            { "STARBUCKS 1 CONCOU LONDON", Category.Subsistence },
            { "STARBUCKS CARD REL 8452703310", Category.Subsistence },
            { "STARBUCKS EASTBOUR EASTBOURNE", Category.Subsistence },
            { "STARBUCKS LONDON", Category.Subsistence },
            { "STARBUCKS LONDON EC2M", Category.Subsistence },
            { "STICKS & BROTH BRISTOL BS1", Category.Subsistence },
            { "TANAKATSU AT RIBON LONDON", Category.Subsistence },
            { "TESCO PFS 3916 EASTBOURNE 2", Category.Subsistence },
            { "TESCO STORES 5158 LONDON", Category.Subsistence },
            { "TESCO STORES 6339 CHINGFORD", Category.Subsistence },
            { "TESCO STORES 6977 WALTHAMSTOW", Category.Subsistence },
            { "SS GT BRITAIN TRAD BRISTOL", Category.Subsistence },
            { "THAI EXPRESS LONDON", Category.Subsistence },
            { "THE ARGYLE LONDON LONDON", Category.Subsistence },
            { "THE JAPANESE CANTE LONDON", Category.Subsistence },
            { "THE VILLAGE LONDON", Category.Subsistence },
            { "VENDING SOLUTIONS SOUTHAMPTON", Category.Subsistence },
            { "WAGAMAMA ROYAL FES LONDON", Category.Subsistence },
            { "WASABI HIGH HOLBOR LONDON", Category.Subsistence },
            { "WWW.JUST-EAT.CO.UK 02067 362061", Category.Subsistence },
            { "YEN LONDON  EC1A", Category.Subsistence },
            { "YOKU SUSHI LIMITED EASTBOURNE", Category.Subsistence },

            { "ECONOMIST SUBSCRIP LONDON", Category.Subscriptions },
            { "INT'L 0067371104 Kindle Unlimited Amazon.co.uk", Category.Subscriptions },
            { "INT'L 0084827059 1105 MEDIA SUBSCRP 818-814-5200 USD 65.00 @ 1.4220  Visa Rate", Category.Subscriptions },
            { "INT'L 0090697151 AMAZON PRIME MEMBE AMZN.CO.UK/PM", Category.Subscriptions },
            
            { "Non-Sterling Transaction Fee", Category.Sundries },

            { "HMRC VAT", Category.Vat },
            
 
        };
        
       
        
    }
}