using System.Collections.Generic;
using Wmg.App.Domain.Models;

namespace Wmg.App.Domain.Categories
{
    public class Hsbc
    {
        public static IDictionary<string, ExpenseCategories> Items = new Dictionary<string, ExpenseCategories>
        {
            {"800 DEGREES LIMITE BRIGHTON", ExpenseCategories.Subsistence},
            {"ABOKADO [A-Z]+ [A-Z]+", ExpenseCategories.Subsistence},
            {"ACCOUNTSNET", ExpenseCategories.Exclude},
            {"AGAPE MINISTRIES L 1041020 CHEOL BAEK", ExpenseCategories.Charity},
            {"AIRBNB\\s[0-9]+", ExpenseCategories.Travel},
            {"ALBION 020 7583 0227", ExpenseCategories.Subsistence},
            {"ANDREW CHAA ANDY HALIFAX", ExpenseCategories.Dividend},
            {"ANDREW TSB EMPLOYEE", ExpenseCategories.Dividend},
            {"APPLEGREEN PALMERS PALMERS GREEN", ExpenseCategories.Subsistence},
            {"APPLE STORE R[0-9]+ LONDON", ExpenseCategories.Equipment},
            {"ARK CONVENIENCES LONDON  E4", ExpenseCategories.Subsistence},
            {"ARGOS LTD CHEAPSIDE EC2", ExpenseCategories.Equipment},
            {"AROMA CHINGFORD LT CHINGFORD", ExpenseCategories.Subsistence},
            {"AMT COFFEE LONDON [0-9]+", ExpenseCategories.Subsistence},
            {"BANH MI BAY LONDON", ExpenseCategories.Subsistence},
            {"BARTS SERCO PARKING PERMI", ExpenseCategories.CarParking},
            {"BHCC-PAYPHONEPARKI BRIGHTON", ExpenseCategories.CarParking},
            {"BILLS EASTBOURNE EASTBOURNE", ExpenseCategories.Subsistence},
            {"BIRLEYS SANDWICHES LONDON", ExpenseCategories.Subsistence},
            {"BOOTS0803 LONDON", ExpenseCategories.Subsistence},
            {"BP CHURCH VIEW CON TUNBRIDGE WEL", ExpenseCategories.Subsistence},
            {"Breeze Mezze Resta London", ExpenseCategories.Subsistence},
            {"BRISTOL CITY COUNC BRISTOL", ExpenseCategories.CarParking},
            {"BRISTOL PACKET LTD BRISTOL", ExpenseCategories.CarParking},
            {"BROWNS LONDON  18840", ExpenseCategories.Subsistence},
            {"BT WIFI WITH FON INTERNET", ExpenseCategories.Communication},
            {"BUCKHURST INN BUCKHURST HIL", ExpenseCategories.Subsistence},
            {"BURGER KING LONDON", ExpenseCategories.Subsistence},
            {"B & Q [0-9]+ LONDON", ExpenseCategories.Equipment},
            {"CAFFE NERO 337 VIC LONDON", ExpenseCategories.Subsistence},
            {"CAFFE NERO BRISTOL - CLI", ExpenseCategories.Subsistence},
            {"CAFFE NERO EASTBOU EASTBOURNE", ExpenseCategories.Subsistence},
            {"CAFFE VERGANO 1882 LONDON  WC1V", ExpenseCategories.Subsistence},
            {"CAMBRIDGE THEATRE LONDON  WC2", ExpenseCategories.Subsistence},
            {"CAMINO BANKSIDE LONDON", ExpenseCategories.Subsistence}, 
            {"CENTREPOINT FOOD LONDON", ExpenseCategories.Subsistence},
            {"CHEEKY CHICOS LIMI LONDON  EC4V", ExpenseCategories.Subsistence},
            {"CINEWORLD ENF CP 0844 815 7747", ExpenseCategories.Subsistence},
            {"CRUSSH FIT FOOD LONDON  EC4M", ExpenseCategories.Subsistence},
            {"A CLOUD GURU TWICKENHAM", ExpenseCategories.Software},
            {"CO-OP GROUP FOOD [A-Z0-9]+", ExpenseCategories.Subsistence},
            {"CO-OP GROUP PETROL [A-Z0-9]+", ExpenseCategories.Mileage},
            {"COSTA @ TESCO 4303 LONDON  E4", ExpenseCategories.Subsistence},
            {"COSTA COFFEE CHINGFORD", ExpenseCategories.Subsistence},
            {"COSTA COFFEE WALTHAMSTOW", ExpenseCategories.Subsistence},
            {"CURRYS ONLINE HEMEL HEMPSTE", ExpenseCategories.Equipment},
            {"DART-CHARGE GOV.UK/DART-C", ExpenseCategories.CarParking},
            {"DPT OF COFFEE & SO LONDON EC1N 7", ExpenseCategories.Subsistence},
            {"DELICE DE FRANCE B LONDON", ExpenseCategories.Subsistence},
            {"EAT 1997 LONDON EC2M", ExpenseCategories.Subsistence},
            {"ECONOMIST SUBSCRIP LONDON", ExpenseCategories.Subscriptions},
            {"EUROSTAR INTERNET LONDON", ExpenseCategories.PublicTransport},
            {"FRANCO MANCA LONDON", ExpenseCategories.Subsistence},
            {"FIVE GUYS LONDON", ExpenseCategories.Subsistence},
            {"Fusciardis Ice Cre Eastbourne", ExpenseCategories.Subsistence},
            {"GIFFGAFF WWW.GIFFGAFF", ExpenseCategories.Communication},
            {"GIVE ME EXTRA EASTBOURNE", ExpenseCategories.Subsistence},
            {"GBK GREENWICH LONDON  SE10", ExpenseCategories.Subsistence},
            {"GOOGLE \\*Google Sto g.co/helppay#", ExpenseCategories.Subsistence},
            {"GREGGS CHINGFORD", ExpenseCategories.Subsistence},
            {"H3G", ExpenseCategories.Communication},
            {"HARE AND TORTOISE LONDON", ExpenseCategories.Subsistence},
            {"HANADAL LTD LONDON  WC1V", ExpenseCategories.Subsistence},
            {"HIGHAMS LOUNGE LONDON", ExpenseCategories.Subsistence},
            {"H/VSTER CHINGFORD 0208 5292990", ExpenseCategories.Subsistence},
            {"HILLSONG CHURCH 0207 3849200", ExpenseCategories.Charity},
            {"H MART MINI LONDON", ExpenseCategories.Subsistence},
            {"HMRC VAT", ExpenseCategories.Vat},
            {"ICELAND PENGE", ExpenseCategories.Subsistence},
            {"IKEA LIMITED EDMONTON REST", ExpenseCategories.Subsistence},
            {"IKEA LIMITED EDMONTON(\\sSACA)?", ExpenseCategories.Fixture},
            {"INN OF COURT LONDON EC1N", ExpenseCategories.Subsistence},
            {"INT'L [0-9]+ Pluralsight [0-9|-]+ USD [0-9|\\.]+ @[0-9|\\.]+ Visa Rate", ExpenseCategories.Software},
            {"INT'L [0-9]+ Amazon Digital Dwn [0-9|-]+", ExpenseCategories.Book},
            {"INT'L [0-9]+ Amazon.co.uk .*AMAZON.CO.UK", ExpenseCategories.Equipment},
            {"INT'L [0-9]+ AMZN Mktp UK.*", ExpenseCategories.Equipment},
            {"INT'L [0-9]+ AMZ\\*Amazon.co.uk AMAZON.CO.UK", ExpenseCategories.Equipment},
            {"INT'L [0-9]+ AMZ\\*JEDirect UK 800-279-6620", ExpenseCategories.Equipment},
            {"INT'L [0-9]+ AMAZON SVCS EU-UK AMAZON.CO.UK", ExpenseCategories.Equipment},
            {"INT'L [0-9]+ Amazon web service aws.amazon.co USD 15.59 @ 1.3532  Visa Rate", ExpenseCategories.Software},
            {"INT'L [0-9]+ Amazon UK Marketpl 800-279-6620", ExpenseCategories.Equipment},
            {"INT'L [0-9]+ AMAZON EU AMAZON.C AMAZON.CO.UK", ExpenseCategories.Equipment},
            {"INT'L [0-9]+ Amazon UK Marketpl [0-9|-]+", ExpenseCategories.Equipment},
            {"INT'L [0-9]+ Amazon UK Retail AMAZON.CO.UK", ExpenseCategories.Equipment},
            {"INT'L [0-9]+ AMAZON PRIME MEMBE AMZN.CO.UK/PM", ExpenseCategories.Subscriptions},
            {"INT'L [0-9]+ Amazon web service aws.amazon.co USD 0.61 @ 1.3863  Visa Rate", ExpenseCategories.Software},
            {"INT'L [0-9]+ AWS EMEA (#[0-9|\\s])*aws\\.amazon\\.co USD [0-9|\\.]+ @ [0-9|\\.]+  Visa Rate", ExpenseCategories.Software},
            {"INT'L [0-9]+ AUCHAN VAL D'EUROP 77000", ExpenseCategories.Subsistence},
            {"INT'L [0-9]+ HOTEL FRANCAIS .+", ExpenseCategories.Travel},
            {"INT'L [0-9]+ PAYGATE_INTERNET S SEOUL KRW[0-9]+ @[0-9|\\.]+ Visa R", ExpenseCategories.Book},
            {"INT'L [0-9]+ UBER EATS [A-Z0-9]+ HE help.uber.com", ExpenseCategories.Subsistence},
            {"INT'L [0-9]+ UBER\\s+\\*EATS [A-Z0-9]+ [0-9|-]+", ExpenseCategories.Subsistence},
            {"INT'L [0-9]+ UBER TRIP [A-Z0-9]+ HE help\\.uber\\.com(.+)?", ExpenseCategories.PublicTransport},
            {"INT'L [0-9]+ ITUNES.COM/BILL ITUNES.COM", ExpenseCategories.Software},
            {"INT'L [0-9]+ Kindle Unltd .*", ExpenseCategories.Subscriptions},
            {"INT'L [0-9]+ 1105 MEDIA SUBSCRP 818-814-5200 USD 65.00 @ 1.4220  Visa Rate", ExpenseCategories.Subscriptions},
            {"INT'L [0-9]+ NAME-CHEAP.COM WWW.NAMECHEAP USD [0-9|\\.]+ @ [0-9|\\.]+  Visa Rate", ExpenseCategories.Software},
            {"ISMASH UK TRADING LONDON", ExpenseCategories.Equipment},
            {"IZ \\*BENDENE LIMITE london", ExpenseCategories.Subsistence},
            {"IZ \\*DELICE Emilia LONDON", ExpenseCategories.Subsistence},
            {"IZ \\*Foodgangnamsty New malden", ExpenseCategories.Subsistence},
            {"IZ \\*Handcrafted Co London", ExpenseCategories.Subsistence},
            {"IZ \\*KOTTU AND HOPP London", ExpenseCategories.Subsistence},
            {"IZ \\*PRIME GELATO L London", ExpenseCategories.Subsistence},
            {"IZ \\*THE GREEN CAFE HASTINGS", ExpenseCategories.Subsistence},
            {"IZ \\*Urban Ground EASTBOURNE", ExpenseCategories.Subsistence},
            {"IZ \\*WOKIT LIMITED London", ExpenseCategories.Subsistence},
            {"KFC - ARCHWAY ARCHWAY", ExpenseCategories.Subsistence},
            {"Just Eat London", ExpenseCategories.Subsistence},
            {"JUSTPARK LONDON", ExpenseCategories.CarParking},
            {"KIMCHEE HOLBORN LONDON", ExpenseCategories.Subsistence},
            {"KIMCHEE TO GO 106 LONDON", ExpenseCategories.Subsistence},
            {"LABOITE LONDON  E4", ExpenseCategories.Subsistence},
            {"Le Petit Corner Leytonstone", ExpenseCategories.Subsistence},
            {"LIME ORANGE LONDON  SW1V", ExpenseCategories.Subsistence},
            {"LITTLE ITALY EASTBOURNE BN", ExpenseCategories.Subsistence},
            {"LOTUS LEAF LONDON", ExpenseCategories.Subsistence},
            {"M&S SIMPLY FOOD - .+", ExpenseCategories.Subsistence},
            {"MARKS&SPENCER PLC [A-Z]+", ExpenseCategories.Subsistence},
            {"MARRAKECH DELIGHT LONDON", ExpenseCategories.Subsistence},
            {"MCDONALD'?S [A-Z]+ \\s? [A-Z|0-9]+", ExpenseCategories.Subsistence},
            {"MORRISON PETROL LONDON E4 001", ExpenseCategories.Subsistence},
            {"MOTO READING EAST READING", ExpenseCategories.Subsistence},
            {"MOTO READING WT CO READING", ExpenseCategories.Subsistence},
            {"NANDOS .+", ExpenseCategories.Subsistence},
            {"NISA EASTBOURNE", ExpenseCategories.Subsistence},
            {"NEWDAY LIMITED LONDON", ExpenseCategories.Exclude},
            {"Non-Sterling Transaction Fee", ExpenseCategories.Sundries},
            {"NOO NOODLES LONDON", ExpenseCategories.Subsistence},
            {"PATISSERIE VALERIE EASTBOURNE", ExpenseCategories.Subsistence},
            {"PIZZAEXPRESS RESTA WALTHANSTOW", ExpenseCategories.Subsistence},
            {"OYSTER [A-Z|-]+ [A-Z]+ [0-9]+ [0-9]+", ExpenseCategories.PublicTransport},
            {"PAUL UK ST PAULS LONDON", ExpenseCategories.Subsistence},
            {"PAYBYPHONE HATFIELD", ExpenseCategories.CarParking},
            {"PAYPAL \\*[A-Z]+ [0-9]+", ExpenseCategories.Equipment},
            {"PHO [A-Z|'|\\s]+ [A-Z]+", ExpenseCategories.Subsistence},
            {"PIZZA EXPRESS [A-Z]+ [A-Z]+", ExpenseCategories.Subsistence},
            {"POST OFFICE COUNTE LONDON", ExpenseCategories.Postage},
            {"PRODUCT SUPPORT AG 0844 800 6080", ExpenseCategories.Insurance},
            {"RINGGO PARKING 18", ExpenseCategories.CarParking},
            {"ROSAS WESTFIELD ST LONDON", ExpenseCategories.Subsistence},
            {"POD LONDON", ExpenseCategories.Subsistence},
            {"POUNDLAND LTD LONDON  E17", ExpenseCategories.Stationery},
            {"PRET A MANGER [0-9|A-Z]* \\s?[A-Z|0-9]*", ExpenseCategories.Subsistence},
            {"SAINSBURYS?('S)? S/MKTS .+]*", ExpenseCategories.Subsistence},
            {"SATAY STREET 02074260017", ExpenseCategories.Subsistence},
            {"SHAKE SHACK WATFORD", ExpenseCategories.Subsistence},
            {"SHELL LARKSHALL RD CHINGFORD", ExpenseCategories.Subsistence},
            {"SHORYU STRATFORD LONDON", ExpenseCategories.Subsistence},
            {"SODO PIZZA LONDON", ExpenseCategories.Subsistence},
            {"SPICY & GRILL LONDON NW11", ExpenseCategories.Subsistence},
            {"Spotify [A-Z|0-9]+ London", ExpenseCategories.Software},
            {"SS GT BRITAIN TRAD BRISTOL", ExpenseCategories.Subsistence},
            {"ST PANCRAS INTL LONDON", ExpenseCategories.PublicTransport},
            {"STARBUCKS .+", ExpenseCategories.Subsistence},
            {"STICKS & BROTH BRISTOL BS1", ExpenseCategories.Subsistence},
            {"SUBWAY LONDON .+", ExpenseCategories.Subsistence},
            {"SUPPA LONDON  EC1A", ExpenseCategories.Subsistence},
            {"SWEETHEART LONDON  WC2E", ExpenseCategories.Subsistence},
            {"TANAKATSU AT RIBON LONDON", ExpenseCategories.Subsistence},
            {"TESCO PFS 3916 EASTBOURNE 2", ExpenseCategories.Subsistence},
            {"TESCO STORES [0-9]+ [A-Z|\\s]+", ExpenseCategories.Subsistence},
            {"TFL OYST PHOTOCARD 0343 222 1234", ExpenseCategories.PublicTransport},
            {"TFL TRAVEL [A-Z]+ TFL.GOV.UK/CP", ExpenseCategories.PublicTransport},
            {"T G I FRIDAY'S ENFIELD 680", ExpenseCategories.Subsistence},
            {"THAI EXPRESS LONDON", ExpenseCategories.Subsistence},
            {"THE ARGYLE LONDON LONDON", ExpenseCategories.Subsistence},
            {"THE ASSOCIATION LONDON  EC4M", ExpenseCategories.Subsistence},
            {"THE CHEEKY INDIAN UXBRIDGE", ExpenseCategories.Subsistence},
            {"THE JAPANESE CANTE LONDON", ExpenseCategories.Subsistence},
            {"THE PUNCH TAVERN LONDON", ExpenseCategories.Subsistence},
            {"THE VILLAGE LONDON", ExpenseCategories.Subsistence},
            {"THEWORKS CHINGFORD", ExpenseCategories.Subsistence},
            {"TOSSED LONDON  EC1A", ExpenseCategories.Subsistence},
            {"TRAINLINE LONDON", ExpenseCategories.PublicTransport},
            {"UBER EATS [A-Z|0-9]+ HE help.uber.com", ExpenseCategories.Subsistence},
            {"UBER TRIP [A-Z|0-9]+ HE help.uber.com", ExpenseCategories.PublicTransport},
            {"UPPER CRUST BARRIE LONDON", ExpenseCategories.Subsistence},
            {"VAPIANO [A-Z|\\s]*LONDON.*", ExpenseCategories.Subsistence},
            {"VENDING SOLUTIONS SOUTHAMPTON", ExpenseCategories.Subsistence},
            {"VICTORIA SQUARE HO BRISTOL", ExpenseCategories.PublicTransport},
            {"VIRGIN MEDIA PYMTS", ExpenseCategories.Communication},
            {"WAGAMAMA .*", ExpenseCategories.Subsistence},
            {"WAHACA ST PAULS LONDON", ExpenseCategories.Subsistence},
            {"WASABI .+ LONDON", ExpenseCategories.Subsistence},
            {"WELLBEING KITCHEN LONDON  WC2H", ExpenseCategories.Subsistence},
            {"WWW.ALIEXPRESS.COM INTERNET", ExpenseCategories.Equipment},
            {"WWW.DOMINOS.CO.UK 01908 580000", ExpenseCategories.Subsistence},
            {"WWW.IKEA.COM PETERBOROUGH", ExpenseCategories.Fixture},
            {"WWW.JUST-EAT.CO.UK 02067 362061", ExpenseCategories.Subsistence},
            {"WWW.TFL.GOV.UK 0343 2221234", ExpenseCategories.PublicTransport},
            {"YEN LONDON  EC1A", ExpenseCategories.Subsistence},
            {"YOKU SUSHI LIMITED [A-Z|0-9]+", ExpenseCategories.Subsistence},

        };


    }
}